dist: xenial   #Use light Xenial distro
group: edge  
matrix:        #Will consist of entire project's commands segment wise
    - language: python
      python:
      - "3.6"
      - "3.7"
      - "3.8"
      os:
      - linux
      - windows
      - osx
      install:
        - pip install --editable .
      script:
        - intermine_boot --test
      deploy:
	    on: 
	  branch: master
        provider: s3
        access_key_id: "YOUR AWS ACCESS KEY"
        secret_access_key: "YOUR AWS SECRET KEY"
        bucket: "Intermine"
        skip_cleanup: true
